name: Publish to Skyslycer Repository

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'dependabot') && !contains(github.event.head_commit.message, 'nopush')"
    environment: build
    runs-on: ubuntu-latest
    env:
      HAS_TOKEN: ${{ secrets.REPO_PASSWORD != '' }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build
      - run: mkdir staging && cp build/libs/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
